project:
  type: website

execute:
  freeze: auto

website:
  title: "MyBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wkabbani
      - icon: twitter
        href: https://twitter.com/therealwassimk
format:
  html:
    theme: flatly
    css: styles.css



